@{
        ProcessorArchitecture=''
        Author='James Brundage'
        Description='Windows 7 Resource Kit PowerShell Pack'
        ModuleToProcess='PowerShellPack.psm1'
        RequiredModules=''
        FunctionsToExport='*'
        FileList='PowershellPack.psd1',
            'PowerShellPack.psm1'
        TypesToProcess=''
        DotNetFrameworkVersion=''
        VariablesToExport='*'
        CLRVersion=''
        PowerShellHostVersion=''
        CmdletsToExport='*'
        Copyright='(c) 2009 James Brundage. All rights reserved.'
        PrivateData=''
        PowerShellHostName=''
        FormatsToProcess=''
        RequiredAssemblies=''
        ModuleVersion='1.0'
        GUID='f76efb37-901f-4e16-963c-1e4459b1ac24'
        PowerShellVersion=''
        CompanyName='Microsoft'
        AliasesToExport='*'
        ScriptsToProcess=''
        ModuleList=''
        NestedModules=''
    }
