' Script:    Create_Restore.vbs 
' Purpose:  This script will graphically create a Powershell script based on user input, the powershell script can be run to restore deleted AD Objects 
' Author:   Paperclips     
' Email:    magiconion_M@hotmail.com 
' Date:     Feb 2011 
' Comments: Creating a ps1 script to restore deleted AD objects 
' Notes:     
'            - The recycling feature must be enabled on teh DC that this is run on - At present only available in 2008 R2 
 
Dim objFSO, objFolder, objFile, objWMI, objItem, GUID, x, ShellMessage 
 
' ---------------------------------------------------Set the folder and file name------------------------------------------------------------------- 
strComputer = "." 
strFileName1 = "Commit_Restore.ps1" 
strFileName2 = "Query_Del_Obj.ps1" 
strFolder1 = ".\" 
strPath1 = strFolder1 & strFileName1 
strPath2 = strFolder1 & strFileName2 
 
' ----------------------------------------------------Create the File System Object----------------------------------------------------------------- 
Set objFSO = CreateObject("Scripting.FileSystemObject") 
 
'----------------------------------------------------Check that the strFolder2 folder exists-------------------------------------------------------- 
If objFSO.FolderExists(strFolder1) Then 
Set objFolder = objFSO.GetFolder(strFolder1) 
Else 
Set objFolder = objFSO.CreateFolder(strFolder1) 
End If 
 
If objFSO.FileExists(strFolder1 & strFileName2) Then 
Set objFolder = objFSO.GetFolder(strFolder1) 
Else 
Set objFile = objFSO.CreateTextFile(strFolder1 & strFileName2) 
End If  
 
'----------------------------------------------------Generate the Query.ps1 Script and run Query Script and Open report-------------------------------- 
set objFile = nothing 
set objFolder = nothing 
Set strFileOpen2 = objFSO.CreateTextFile(strPath2, True) 
 
'---------------------generate Script--------------------------------- 
strFileOpen2.WriteLine("import-module activedirectory") 
strFileOpen2.WriteLine("Get-AdObject -filter 'isdeleted -eq $True -and name -ne ""Deleted Objects""' -includeDeletedObjects -property * |Format-List samAccountName,DistinguishedName,LastKnownParent,ObjectGUID,ObjectClass > Deleted_Obj.txt") 
strFileOpen2.Close 
 
'---------------------Run Script that was generated------------------- 
Set objShell = CreateObject("Wscript.Shell") 
objShell.Run("powershell.exe -WindowStyle minimized -noprofile .\Query_Del_Obj.ps1") 
WScript.Sleep(3000) 
 
'------------Open report that was generated by running script--------- 
ShellMessage = MsgBox("Please wait while the report is genereated" & VbNewLine & "The report will open automatically in a text file when the process completes",0,"Please wait") 
WScript.Sleep(7000)  
objShell.Run("notepad.exe .\Deleted_Obj.txt") 
 
'-----------------------------------------------------Check that the strFolder1 folder exists-------------------------------------------------------- 
If objFSO.FolderExists(strFolder1) Then 
Set objFolder = objFSO.GetFolder(strFolder1) 
Else 
Set objFolder = objFSO.CreateFolder(strFolder1) 
End If 
 
If objFSO.FileExists(strFolder1 & strFileName1) Then 
Set objFolder = objFSO.GetFolder(strFolder1) 
Else 
Set objFile = objFSO.CreateTextFile(strFolder1 & strFileName1) 
End If  
' -----Cleanup----- 
 
set objFile = nothing 
set objFolder = nothing 
' -----------------------------------------------------Write the information to the file------------------------------------------------------------ 
 
Set strFileOpen1 = objFSO.CreateTextFile(strPath1, True) 
' -----------------------------------------------------Create script based ojn this Criteria----------------------------------------------------------- 
 
x = MsgBox("Do you want to create the powershell script for restoring Deleted AD Objects?" & VbNewLine & "Please note that you will need the GUID" & VbnewLine & "Also note that any objects deleted prior to 180 days ago, will not be recoverable!" & VbnewLine & "" & VbnewLine & "IMPORTANT: Always restore Parent OU's first (This is because if any child objects exist under an OU, The OU must exist)",4,"Confirmation") 
  
If x = vbyes Then 
    strFileOpen1.WriteLine("import-module activedirectory") 
        Do While x = vbyes 
        Call Criteria 
        x = MsgBox("Would you like to add another GUID",4,"Confirmation") 
    Loop 
End if     
 
strFileOpen1.Close 
'---------------------Run Script that was generated------------------- 
Set objShell = CreateObject("Wscript.Shell") 
 
y = MsgBox("Do you want to commit the script for restoring Deleted AD Objects? " & VbNewLine & "The GUID's entered will be restored",4,"Confirmation") 
  
If y = vbyes Then 
    objShell.Run("powershell.exe -WindowStyle minimized -noprofile .\Commit_Restore.ps1") 
    WScript.Sleep(3000) 
    ShellMessage = MsgBox("The objects have now been restored.",0,"Finished") 
End if     
 
On Error goTo 0 
Function Criteria() 
    GUID = InputBox("Please Enter the GUID you would like to restore", "Input Criteria") 
    strFileOpen1.WriteLine("restore-ADObject -identity " &GUID) 
End Function