function New-ISEMenu {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated By: Ravikanth Chaganti
########################################################################            

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion            

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$checkBox1 = New-Object System.Windows.Forms.CheckBox
$button2 = New-Object System.Windows.Forms.Button
$button1 = New-Object System.Windows.Forms.Button
$textBox3 = New-Object System.Windows.Forms.TextBox
$label3 = New-Object System.Windows.Forms.Label
$textBox2 = New-Object System.Windows.Forms.TextBox
$label2 = New-Object System.Windows.Forms.Label
$textBox1 = New-Object System.Windows.Forms.TextBox
$label1 = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects            

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
$button1_OnClick=
{
    if ($textBox1.Text) {
        $addonName = $textBox1.Text.ToString()
    } else {
        [System.Windows.Forms.MessageBox]::Show("You must supply all parameters")
        return
    }
    if ($textBox2.Text) {
        $addonShortCut = $textBox2.Text.ToString()
    } else {
        $addonShortCut = ""
        return
    }
    if ($textbox3.Text) {
        $scriptBlock = $ExecutionContext.InvokeCommand.NewScriptBlock($textBox3.Text.ToString())
    } else {
        [System.Windows.Forms.MessageBox]::Show("You must supply all parameters")
        return
    }
    $menuItems = $psise.CurrentPowerShellTab.AddOnsMenu.Submenus | Select -ExpandProperty DisplayName
    if ($menuItems -Contains $addonName) {
        [System.Windows.Forms.MessageBox]::Show("Select another Name")
        return
    }            

    try {
        $psISE.CurrentPowerShellTab.AddOnsMenu.SubMenus.Add($addonName,$ScriptBlock,$addonShortCut) | Out-Null
    }
    catch {
        Write-Error $_
        $form1.Close()
        return
    }            

    if ($checkBox1.Checked) {
        $profileText = "`n`#Added by ISE Menu Creator Addon
if (`$psISE) {
`$psISE.CurrentPowerShellTab.AddOnsMenu.SubMenus.Add(`"$addonName`",`{$ScriptBlock`},`"$addonShortCut`") | Out-Null
}
"
Add-Content -Path $profile -Value $profileText
    }            

    $form1.Close()
}
$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
 $form1.WindowState = $InitialFormWindowState
}            

#----------------------------------------------
#region Generated Form Code
$form1.CancelButton = $button2
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 201
$System_Drawing_Size.Width = 458
$form1.ClientSize = $System_Drawing_Size
$form1.ControlBox = $False
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.MaximizeBox = $False
$form1.MinimizeBox = $False
$form1.Name = "form1"
$form1.ShowIcon = $False
$form1.ShowInTaskbar = $False
$form1.Text = "ISE Menu Creator"
$form1.TopMost=$true            

$checkBox1.DataBindings.DefaultDataSourceUpdateMode = 0            

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 136
$checkBox1.Location = $System_Drawing_Point
$checkBox1.Name = "checkBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 181
$checkBox1.Size = $System_Drawing_Size
$checkBox1.TabIndex = 6
$checkBox1.Text = "Add to ISE Profile Script"
$checkBox1.UseVisualStyleBackColor = $True            

$form1.Controls.Add($checkBox1)            

$button2.DataBindings.DefaultDataSourceUpdateMode = 0
$button2.DialogResult = 2            

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 301
$System_Drawing_Point.Y = 166
$button2.Location = $System_Drawing_Point
$button2.Name = "button2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button2.Size = $System_Drawing_Size
$button2.TabIndex = 8
$button2.Text = "Cancel"
$button2.UseVisualStyleBackColor = $True
$button2.add_Click($button2_OnClick)            

$form1.Controls.Add($button2)            

$button1.DataBindings.DefaultDataSourceUpdateMode = 0            

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 76
$System_Drawing_Point.Y = 166
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 7
$button1.Text = "Save"
$button1.UseVisualStyleBackColor = $True
$button1.add_Click($button1_OnClick)            

$form1.Controls.Add($button1)            

$textBox3.AcceptsReturn = $True
$textBox3.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 127
$System_Drawing_Point.Y = 61
$textBox3.Location = $System_Drawing_Point
$textBox3.Multiline = $True
$textBox3.Name = "textBox3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 66
$System_Drawing_Size.Width = 304
$textBox3.Size = $System_Drawing_Size
$textBox3.TabIndex = 5
$textBox3.AcceptsTab = $True            

$form1.Controls.Add($textBox3)            

$label3.DataBindings.DefaultDataSourceUpdateMode = 0            

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 64
$label3.Location = $System_Drawing_Point
$label3.Name = "label3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label3.Size = $System_Drawing_Size
$label3.TabIndex = 4
$label3.Text = "Script Block"            

$form1.Controls.Add($label3)            

$textBox2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 127
$System_Drawing_Point.Y = 35
$textBox2.Location = $System_Drawing_Point
$textBox2.Name = "textBox2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 181
$textBox2.Size = $System_Drawing_Size
$textBox2.TabIndex = 3            

$form1.Controls.Add($textBox2)            

$label2.DataBindings.DefaultDataSourceUpdateMode = 0            

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 38
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 2
$label2.Text = "Shortcut Key"            

$form1.Controls.Add($label2)            

$textBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 127
$System_Drawing_Point.Y = 6
$textBox1.Location = $System_Drawing_Point
$textBox1.Name = "textBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 181
$textBox1.Size = $System_Drawing_Size
$textBox1.TabIndex = 1            

$form1.Controls.Add($textBox1)            

$label1.DataBindings.DefaultDataSourceUpdateMode = 0            

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 0
$label1.Text = "Addon Menu Name"            

$form1.Controls.Add($label1)            

#endregion Generated Form Code            

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null            

} #End Function