USE [master]
GO
/****** Object:  Database [ADGroupManagementDB]    Script Date: 2/26/2013 11:42:13 AM ******/
CREATE DATABASE [ADGroupManagementDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ADGroupManagementDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ADGroupManagementDB.mdf' , SIZE = 4672KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ADGroupManagementDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ADGroupManagementDB_Log.ldf' , SIZE = 4672KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ADGroupManagementDB] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ADGroupManagementDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ADGroupManagementDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ADGroupManagementDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ADGroupManagementDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ADGroupManagementDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ADGroupManagementDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ADGroupManagementDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ADGroupManagementDB] SET  MULTI_USER 
GO
ALTER DATABASE [ADGroupManagementDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ADGroupManagementDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ADGroupManagementDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ADGroupManagementDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ADGroupManagementDB', N'ON'
GO
USE [ADGroupManagementDB]
GO
/****** Object:  Table [dbo].[GroupTable]    Script Date: 2/26/2013 11:42:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GroupTable](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GroupGUID] [nvarchar](50) NOT NULL,
	[GroupSamAccountName] [nvarchar](max) NOT NULL,
	[UserGUID] [nvarchar](50) NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
 CONSTRAINT [PK_ObjectRefs] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserTable]    Script Date: 2/26/2013 11:42:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserTable](
	[UserGUID] [nvarchar](50) NOT NULL,
	[UserSamAccountName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Objects] PRIMARY KEY CLUSTERED 
(
	[UserGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[GroupTable]  WITH CHECK ADD  CONSTRAINT [FK_GroupTable_UserTable] FOREIGN KEY([UserGUID])
REFERENCES [dbo].[UserTable] ([UserGUID])
GO
ALTER TABLE [dbo].[GroupTable] CHECK CONSTRAINT [FK_GroupTable_UserTable]
GO
USE [master]
GO
ALTER DATABASE [ADGroupManagementDB] SET  READ_WRITE 
GO
