USE [master]
GO

/****** Object:  Database [DnsLogDb]    Script Date: 10/1/2012 7:35:57 PM ******/
CREATE DATABASE [DnsLogDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DnsLogDb', FILENAME = N'C:\temp\DnsLogDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DnsLogDb_log', FILENAME = N'C:\temp\DnsLogDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DnsLogDb] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DnsLogDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DnsLogDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DnsLogDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DnsLogDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DnsLogDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DnsLogDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [DnsLogDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DnsLogDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DnsLogDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DnsLogDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DnsLogDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DnsLogDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DnsLogDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DnsLogDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DnsLogDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DnsLogDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DnsLogDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DnsLogDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DnsLogDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DnsLogDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DnsLogDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DnsLogDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DnsLogDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DnsLogDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DnsLogDb] SET RECOVERY FULL 
GO

ALTER DATABASE [DnsLogDb] SET  MULTI_USER 
GO

ALTER DATABASE [DnsLogDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DnsLogDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DnsLogDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DnsLogDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DnsLogDb] SET  READ_WRITE 
GO

